class airboss
{
      tag = "airboss";
      class lhd
      {
            file = "\airboss";

            class GridToStr {};
            class lhd_checkpos {};
            class lhdsiren {};
            class PosToGrid {};
            class VehicleReturn {};
            class VehicleService {};
            class VehicleSpawn {};
            class VehicleSpawnBox {};
            class atc_aliveapproach {};
            class atc_alivedeck {};
            class atc_alivepattern {};
            class atc_alivetakeoff {};
            class atc_ammovehicle {};
            class atc_baseActionsHomer {};
            class atc_baseActionsFlyco {};
            class atc_baseActionsWatchdog {};
            class atc_controller_contact {};
            class atc_controller_newintentions {};
            class atc_controller_changeintentions {};
            class atc_controller_airtransfer {};
            class atc_controller_lhdtransfer {};
            class atc_controller_sitrep {};
            class atc_controller_traffic {};
            class atc_controller_service {};
            class atc_distancetakeoff {};
            class atc_landing {};
            class atc_landing_cancel {};
            class atc_landingapproach {};
            class atc_nearestVector {};
            class atc_position_base {};
            class atc_position_ship {};
            class atc_removePilotActions {};
            class atc_safetakeoff {};
            class atc_takeoff {};
            class atc_takeoff_cancel {};
            class atc_taskalive {};
            class atc_taskalivetask {};
            class atc_tasking_closeairsupport {};
            class atc_tasking_transport {};
            class atc_weather {};
            class land_alivedelivery {};
            class land_aliveplayer {};
            class land_assignpickup {};
            class land_baseActionsWatchdog {};
            class land_cascallsign {};
            class land_closeairsupport {};
            class land_controller_contact {};
            class land_controller_transfer {};
            class land_controller_position {};
            class land_RemoveActionsWatchdog {};
            class land_transport_air {};
            class ui_BayOver {};
            class ui_BaySelect {};
            class ui_BayStatusUpdate {};
            class ui_BayWatch {};
            class ui_debarkationControl {};
            class ui_UpdateListBox {};
            class system_atccontroller {};
            class system_controlRoom {};
            class system_playeralive {};
            class system_vehiclealive {};
      };
};